name: Release Develop to testing deployment

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build-and-release:
    runs-on: self-hosted
    name: Build and release app
    steps:
      - uses: actions/checkout@v3

      - id: docker-build-and-push
        name: Build and publish on ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 434190342226.dkr.ecr.us-east-1.amazonaws.com
          docker buildx build . -f build/Dockerfile -t resume-webserver/webserver
          docker tag resume-webserver/webserver:latest 434190342226.dkr.ecr.us-east-1.amazonaws.com/resume-webserver/webserver:develop
          docker push 434190342226.dkr.ecr.us-east-1.amazonaws.com/resume-webserver/webserver:develop

      - id: apply
        name: Plan Nomad Job File
        run: |
          OUTPUT=$(nomad job run "deployments/testing.nomad")
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "${OUTPUT}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
